[package]
name = "rush"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
lazy_static = "1.5.0"
regex = "1.11.3"
serde_json = "1.0.145"
